#pragma once

.type irType =
      Any {}
    | Bottom {}
    | Even {}
    | Negative {}
    | NonNegative {}
    | NonPositive {}
    | Positive {}
    | UnEven {}
    | Zero {}

.functor irTypeLub(t1: irType, t2: irType): irType stateful
.functor irTypeGlb(t1: irType, t2: irType): irType stateful

.lattice irType<> {
    Bottom -> $Bottom(),
    Lub -> @irTypeLub(_,_),
    Glb -> @irTypeGlb(_,_),
    Top -> $Any()
}